import { Plus_Jakarta_Sans } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import { CProviders } from "../CProvider";
import Header from "@/components/basic-ui/Header";
import Footer from "@/components/basic-ui/Footer";
import AuthContextProvider from "@/context/AuthContext";
import "react-toastify/dist/ReactToastify.css";

const plus_jakarta_sans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={plus_jakarta_sans.className}>
        <CProviders>
          <AuthContextProvider>
            <Header />
            {children}
            <Footer />
          </AuthContextProvider>
        </CProviders>
      </body>
    </html>
  );
}
